{
  "hash": "50016daa7fb4234871b66dadb7e7efa2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Jonah Fruchtman\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n---\n\n## The question\n\n**In the following report, I will be investigating commuting patterns by race/ethnicity via public transportation in New Jersey, and ask which counties and ethnicities are measured most and least reliably. Since I will specifically be paying attention to margin of error, I cannot directly calculate percentage of people who commute via public transportation, and so will rely on the absolute number and will use total commuters by race/ethnicity as a point of comparison. **\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars <- load_variables(2023, \"acs5\")\nView(vars)\nNJ <- \"NJ\"\nvariables <- c(\n  total_white = \"B08505H_001\",\n  transp_white = \"B08505H_004\",\n  total_black = \"B08505B_001\",\n  transp_black = \"B08505B_004\",\n  total_asian = \"B08505D_001\",\n  transp_asian = \"B08505D_004\",\n  total_hisp = \"B08505I_001\",\n  transp_hisp = \"B08505I_004\",\n  pop   = \"B01003_001\")\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = variables,\n  state = \"NJ\",\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21 20\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 20\n  GEOID NAME  total_whiteE total_whiteM transp_whiteE transp_whiteM total_blackE\n  <chr> <chr>        <dbl>        <dbl>         <dbl>         <dbl>        <dbl>\n1 34001 Atla…        72236         1962           684           162        17436\n2 34003 Berg…       234006         3613          2371           395        36715\n3 34005 Burl…       136774         2930           531           248        33962\n4 34007 Camd…       136011         3037          1239           239        35323\n5 34009 Cape…        35196         1260           190            88         2131\n6 34011 Cumb…        33613         1292           198           109         8413\n# ℹ 13 more variables: total_blackM <dbl>, transp_blackE <dbl>,\n#   transp_blackM <dbl>, total_asianE <dbl>, total_asianM <dbl>,\n#   transp_asianE <dbl>, transp_asianM <dbl>, total_hispE <dbl>,\n#   total_hispM <dbl>, transp_hispE <dbl>, transp_hispM <dbl>, popE <dbl>,\n#   popM <dbl>\n```\n\n\n:::\n:::\n\n\nNew Jersey has 21 counties; Originally, my data frame had 168 rows, as it was \"long\" data and therefore had a row for every variable within a county. However, I then pulled it as \"wide\" data using the \"output\" command so that there there would be one row per county and the variables would be columns.\n\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, I calculated it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(\n    moe_p_ttl_white = total_whiteM / total_whiteE *100,\n    moe_p_transp_white = transp_whiteM / transp_whiteE *100,\n    moe_p_ttl_black = total_blackM / total_blackE *100,\n    moe_p_transp_black = transp_blackM / transp_blackE *100,\n    moe_p_ttl_asian = total_asianM / total_asianE *100,\n    moe_p_transp_asian = transp_asianM / transp_asianE *100,\n    moe_p_ttl_hisp = total_hispM / total_hispE *100,\n    moe_p_transp_hisp = transp_hispM / transp_hispE *100)\n```\n:::\n\n\n\nI then organized the data by least to most reliable by each ethnicity/race and listed the least reliable in each category at the end.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total White\ncounty_data %>%\n  arrange(desc(moe_p_ttl_white)) %>%\n  select(NAME, total_whiteE, total_whiteM, moe_p_ttl_white) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          total_whiteE total_whiteM moe_p_ttl_white\n   <chr>                                <dbl>        <dbl>           <dbl>\n 1 Salem County, New Jersey             17835          963            5.40\n 2 Warren County, New Jersey            29708         1215            4.09\n 3 Cumberland County, New Jersey        33613         1292            3.84\n 4 Cape May County, New Jersey          35196         1260            3.58\n 5 Sussex County, New Jersey            38922         1344            3.45\n 6 Hunterdon County, New Jersey         43888         1343            3.06\n 7 Atlantic County, New Jersey          72236         1962            2.72\n 8 Passaic County, New Jersey           81897         2131            2.60\n 9 Hudson County, New Jersey           106537         2535            2.38\n10 Gloucester County, New Jersey        90905         2063            2.27\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#White Transportation\ncounty_data %>%\n  arrange(desc(moe_p_transp_white)) %>%\n  select(NAME, transp_whiteE, transp_whiteM, moe_p_transp_white) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          transp_whiteE transp_whiteM moe_p_transp_white\n   <chr>                                 <dbl>         <dbl>              <dbl>\n 1 Salem County, New Jersey                 34            28               82.4\n 2 Sussex County, New Jersey               129           102               79.1\n 3 Hunterdon County, New Jersey            173           125               72.3\n 4 Warren County, New Jersey                69            38               55.1\n 5 Cumberland County, New Jersey           198           109               55.1\n 6 Burlington County, New Jersey           531           248               46.7\n 7 Cape May County, New Jersey             190            88               46.3\n 8 Somerset County, New Jersey             491           210               42.8\n 9 Ocean County, New Jersey                621           251               40.4\n10 Gloucester County, New Jersey           564           225               39.9\n```\n\n\n:::\n:::\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Black\ncounty_data %>%\n  arrange(desc(moe_p_ttl_black)) %>%\n  select(NAME, total_blackE, total_blackM, moe_p_ttl_black) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          total_blackE total_blackM moe_p_ttl_black\n   <chr>                                <dbl>        <dbl>           <dbl>\n 1 Sussex County, New Jersey             1646          374           22.7 \n 2 Warren County, New Jersey             2161          456           21.1 \n 3 Hunterdon County, New Jersey          2090          399           19.1 \n 4 Cape May County, New Jersey           2131          344           16.1 \n 5 Salem County, New Jersey              3836          574           15.0 \n 6 Cumberland County, New Jersey         8413          755            8.97\n 7 Gloucester County, New Jersey        15852         1380            8.71\n 8 Ocean County, New Jersey              7150          598            8.36\n 9 Somerset County, New Jersey          20800         1519            7.30\n10 Monmouth County, New Jersey          18721         1249            6.67\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Black Transportation\ncounty_data %>%\n  arrange(desc(moe_p_transp_black)) %>%\n  select(NAME, transp_blackE, transp_blackM, moe_p_transp_black) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          transp_blackE transp_blackM moe_p_transp_black\n   <chr>                                 <dbl>         <dbl>              <dbl>\n 1 Sussex County, New Jersey                 4             7              175  \n 2 Hunterdon County, New Jersey              4             6              150  \n 3 Warren County, New Jersey                27            33              122. \n 4 Cape May County, New Jersey             171           160               93.6\n 5 Cumberland County, New Jersey           226           188               83.2\n 6 Salem County, New Jersey                 58            43               74.1\n 7 Ocean County, New Jersey                105            77               73.3\n 8 Burlington County, New Jersey           642           301               46.9\n 9 Somerset County, New Jersey             718           335               46.7\n10 Monmouth County, New Jersey             384           161               41.9\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Asian\ncounty_data %>%\n  arrange(desc(moe_p_ttl_asian)) %>%\n  select(NAME, total_asianE, total_asianM, moe_p_ttl_asian) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          total_asianE total_asianM moe_p_ttl_asian\n   <chr>                                <dbl>        <dbl>           <dbl>\n 1 Cape May County, New Jersey            939          261           27.8 \n 2 Warren County, New Jersey             1356          293           21.6 \n 3 Cumberland County, New Jersey         1159          234           20.2 \n 4 Sussex County, New Jersey             1330          203           15.3 \n 5 Hunterdon County, New Jersey          3085          390           12.6 \n 6 Gloucester County, New Jersey         5725          590           10.3 \n 7 Ocean County, New Jersey              5681          492            8.66\n 8 Burlington County, New Jersey        12456          831            6.67\n 9 Atlantic County, New Jersey           8651          575            6.65\n10 Passaic County, New Jersey           12807          773            6.04\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Asian Transportation\ncounty_data %>%\n  arrange(desc(moe_p_transp_asian)) %>%\n  select(NAME, transp_asianE, transp_asianM, moe_p_transp_asian) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          transp_asianE transp_asianM moe_p_transp_asian\n   <chr>                                 <dbl>         <dbl>              <dbl>\n 1 Cape May County, New Jersey               0            30              Inf  \n 2 Sussex County, New Jersey                 0            30              Inf  \n 3 Warren County, New Jersey                 0            30              Inf  \n 4 Hunterdon County, New Jersey             22            31              141. \n 5 Burlington County, New Jersey            12            15              125  \n 6 Gloucester County, New Jersey           160           140               87.5\n 7 Ocean County, New Jersey                 49            40               81.6\n 8 Monmouth County, New Jersey             259           163               62.9\n 9 Cumberland County, New Jersey           169            95               56.2\n10 Somerset County, New Jersey             325           177               54.5\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Hispanic or Latino\ncounty_data %>%\n  arrange(desc(moe_p_ttl_hisp)) %>%\n  select(NAME, total_hispE, total_hispM, moe_p_ttl_hisp) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          total_hispE total_hispM moe_p_ttl_hisp\n   <chr>                               <dbl>       <dbl>          <dbl>\n 1 Salem County, New Jersey             2542         410          16.1 \n 2 Cape May County, New Jersey          5242         653          12.5 \n 3 Warren County, New Jersey            4866         569          11.7 \n 4 Sussex County, New Jersey            5357         561          10.5 \n 5 Hunterdon County, New Jersey         5537         528           9.54\n 6 Gloucester County, New Jersey       15259         965           6.32\n 7 Cumberland County, New Jersey       16459        1019           6.19\n 8 Atlantic County, New Jersey         20894        1172           5.61\n 9 Burlington County, New Jersey       22708        1235           5.44\n10 Camden County, New Jersey           31831        1496           4.70\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Hispanic or Latino Transportation\ncounty_data %>%\n  arrange(desc(moe_p_transp_hisp)) %>%\n  select(NAME, transp_hispE, transp_hispM, moe_p_transp_hisp) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          transp_hispE transp_hispM moe_p_transp_hisp\n   <chr>                                <dbl>        <dbl>             <dbl>\n 1 Sussex County, New Jersey                1            6             600  \n 2 Warren County, New Jersey               19           24             126. \n 3 Salem County, New Jersey                28           34             121. \n 4 Cape May County, New Jersey            143          163             114. \n 5 Gloucester County, New Jersey           86           91             106. \n 6 Hunterdon County, New Jersey           103           82              79.6\n 7 Cumberland County, New Jersey          271          167              61.6\n 8 Somerset County, New Jersey            400          227              56.8\n 9 Ocean County, New Jersey               479          252              52.6\n10 Burlington County, New Jersey          304          153              50.3\n```\n\n\n:::\n:::\n\n\n\nThere were a number of unreliable counties that depend on race/ethnicity and whether we were looking at only commuters via public transportation or total commuters.\n\nBelow are the following counties with the largest ratio of margin to error to estimate, in percent:\n\n*White*\nTotal: Salem County: 5.40%\nTransportation: Salem County: 82.4%\n\n*Black*\nTotal: Sussex County: 22.7%\nTransportation: Sussex County: 175%\n\n*Asian*\nTotal: Cape May County: 27.8%\nTransportation: Cape May County: Undefined (as there was an estimated 0 riders, with a 30 person margin of error)\n\n*Hipanic/Latino*\nTotal: Salem County: 16.1\nTransportation: Sussex County: 600\n\n\n---\n\n## Sorting counties into reliability categories\n\nGiven that we have two divisions of our data (1) total commuters and (2) public transportation users, which carry very different spreads of reliability, I decided to use two different reliability scales across races/ethnicity. \n\nTo choose cutoffs for categories, I looked at two histograms of the data:\n\n::: {.cell}\n\n```{.r .cell-code}\nmoe_p_ttl <- c(county_data$moe_p_ttl_white, county_data$moe_p_ttl_black, county_data$moe_p_ttl_asian, county_data$moe_p_ttl_hisp)\n\nmoe_p_ttl_hist <- hist(moe_p_ttl, col=\"orange\",main=\"MOE Percentage (Total)\", breaks = seq(0,40, 2))\n```\n\n::: {.cell-output-display}\n![](assignment2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmoe_p_transp <- c(county_data$moe_p_transp_white, county_data$moe_p_transp_black, county_data$moe_p_transp_asian, county_data$moe_p_transp_hisp)\n\nmoe_p_transp_hist <- hist(moe_p_transp, col=\"blue\",main=\"MOE Percentage (Transportation)\", breaks = seq(0,600, 20))\n```\n\n::: {.cell-output-display}\n![](assignment2_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n:::\n\n\nAs we can see in (1), the margin of error ratio (in percent) for all commuters  (combined), is relatively right-skewed, with most of the data below 10. It therefore seems justifiable to create the following categories: \n- < 10 = High confidence\n- < 20 = Moderate confidence (I chose 8 as there is generally a major increase after 8%)\n- > 20 = Low confidence\n\nFor (2), which is also right-skewed, and has an outlier at 600, it seems justifiable to have the following categories\n- < 40 = High confidence\n- < 80 = Medium confidence\n- < 80 = Low confidence\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total White categories\ncounty_data <- county_data %>%\n  mutate(reliability_ttl_white = case_when(\n    moe_p_ttl_white < 10  ~ \"High confidence\",\n    moe_p_ttl_white < 20 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_ttl_white)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  reliability_ttl_white     n\n  <chr>                 <int>\n1 High confidence          21\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Black Categories\ncounty_data <- county_data %>%\n  mutate(reliability_ttl_black = case_when(\n    moe_p_ttl_black < 10  ~ \"High confidence\",\n    moe_p_ttl_black < 20 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_ttl_black)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_ttl_black     n\n  <chr>                 <int>\n1 High confidence          16\n2 Low confidence            2\n3 Moderate                  3\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Asian Categories\ncounty_data <- county_data %>%\n  mutate(reliability_ttl_asian = case_when(\n    moe_p_ttl_asian < 10  ~ \"High confidence\",\n    moe_p_ttl_asian < 20 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_ttl_asian)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_ttl_asian     n\n  <chr>                 <int>\n1 High confidence          14\n2 Low confidence            4\n3 Moderate                  3\n```\n\n\n:::\n:::\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Hispanic/Latino Categories\ncounty_data <- county_data %>%\n  mutate(reliability_ttl_hisp = case_when(\n    moe_p_ttl_hisp < 10  ~ \"High confidence\",\n    moe_p_ttl_hisp < 20 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_ttl_hisp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  reliability_ttl_hisp     n\n  <chr>                <int>\n1 High confidence         17\n2 Moderate                 4\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#White Transportation Categories\ncounty_data <- county_data %>%\n  mutate(reliability_transp_white = case_when(\n    moe_p_transp_white < 40  ~ \"High confidence\",\n    moe_p_transp_white < 80 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_transp_white)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_transp_white     n\n  <chr>                    <int>\n1 High confidence             12\n2 Low confidence               1\n3 Moderate                     8\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Black Transportation Categories\ncounty_data <- county_data %>%\n  mutate(reliability_transp_black = case_when(\n    moe_p_transp_black < 40  ~ \"High confidence\",\n    moe_p_transp_black < 80 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_transp_black)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_transp_black     n\n  <chr>                    <int>\n1 High confidence             11\n2 Low confidence               5\n3 Moderate                     5\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Asian Transportation Categories\ncounty_data <- county_data %>%\n  mutate(reliability_transp_asian = case_when(\n    moe_p_transp_asian < 40  ~ \"High confidence\",\n    moe_p_transp_asian < 80 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_transp_asian)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_transp_asian     n\n  <chr>                    <int>\n1 High confidence              9\n2 Low confidence               8\n3 Moderate                     4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Hispanic/Latino Transportation Categories\ncounty_data <- county_data %>%\n  mutate(reliability_transp_hisp = case_when(\n    moe_p_transp_hisp < 40  ~ \"High confidence\",\n    moe_p_transp_hisp < 80 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability_transp_hisp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability_transp_hisp     n\n  <chr>                   <int>\n1 High confidence            11\n2 Low confidence              5\n3 Moderate                    5\n```\n\n\n:::\n:::\n\n\n\n\nReliability of counties differs both between and within race and ethnicity. As can be seen in the charts above, there is the highest reliability of white commuters -- both total and public transit. However, when looking at white public transportation riders, the number of counties with low confidence jumps to 8 counties and high confidence plummets by 9 counties. While there is high confidence for total Black commuters in 16 out of 21 counties, this confidence drops to only 11 counties for those who commute via public transportation. Asian and Hispanic/Latino show similar trends, with each also dropping in counties with high confidence and gaining in moderate and low confidence. \n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this, I compared the average population of counties in each reliability category.\n\nI used group_by by county and reliability per race/ethnicity, and summarized by average population in order to isolate just the average populations and count for each confidence level. I then arranged it by average population in descending order in order to better assess the change in decreasing average populations to confidence levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total White\ncounty_data %>%\n  group_by(reliability_ttl_white) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  reliability_ttl_white n_counties avg_population\n  <chr>                      <int>          <dbl>\n1 High confidence               21        441286.\n```\n\n\n:::\n:::\n\n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Black\ncounty_data %>%\n  group_by(reliability_ttl_black) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability_ttl_black n_counties avg_population\n  <chr>                      <int>          <dbl>\n1 High confidence               16        545125.\n2 Low confidence                 2        127678.\n3 Moderate                       3         96552.\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Asian\ncounty_data %>%\n  group_by(reliability_ttl_asian) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability_ttl_asian n_counties avg_population\n  <chr>                      <int>          <dbl>\n1 High confidence               14        590327.\n2 Low confidence                 4        105840.\n3 Moderate                       3        193023 \n```\n\n\n:::\n:::\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total Hispanic/Latino\ncounty_data %>%\n  group_by(reliability_ttl_hisp) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  reliability_ttl_hisp n_counties avg_population\n  <chr>                     <int>          <dbl>\n1 High confidence              17        520674.\n2 Moderate                      4        103891 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Transportation White\ncounty_data %>%\n  group_by(reliability_transp_white) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability_transp_white n_counties avg_population\n  <chr>                         <int>          <dbl>\n1 High confidence                  12        592685.\n2 Low confidence                    1         64973 \n3 Moderate                          8        261227.\n```\n\n\n:::\n:::\n\n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Transportation Black\ntransBlack <- county_data %>%\n  group_by(reliability_transp_black) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n:::\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Transportation Asian\ncounty_data %>%\n  group_by(reliability_transp_asian) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability_transp_asian n_counties avg_population\n  <chr>                         <int>          <dbl>\n1 High confidence                   9        626674.\n2 Low confidence                    8        245022 \n3 Moderate                          4        416694.\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Transportation Hispanic/Latino\ncounty_data %>%\n  group_by(reliability_transp_hisp) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability_transp_hisp n_counties avg_population\n  <chr>                        <int>          <dbl>\n1 High confidence                 11        618884.\n2 Low confidence                   5        144014.\n3 Moderate                         5        347845.\n```\n\n\n:::\n:::\n\n\n\nAs can be seen in the tables above, the average population of high-confidence counties varies by both user type (total and public transportation) and by race/ethnicity, but all are within ~400,000-600,000 people. With the exception of Total Black commuters, the average population of counties in each reliability category decreases as confidence dims. Said otherwise, we are more confident when there is a higher average population.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#All Commuters\nRelbyPop <- county_data %>%\n  group_by(NAME, reliability_ttl_white, reliability_ttl_black, reliability_ttl_asian, reliability_ttl_hisp) %>%\n  summarize(\n    popE\n  ) %>%\n  arrange(desc(popE)) %>%\n  print(n = 21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 × 6\n# Groups:   NAME, reliability_ttl_white, reliability_ttl_black,\n#   reliability_ttl_asian [21]\n   NAME        reliability_ttl_white reliability_ttl_black reliability_ttl_asian\n   <chr>       <chr>                 <chr>                 <chr>                \n 1 Bergen Cou… High confidence       High confidence       High confidence      \n 2 Middlesex … High confidence       High confidence       High confidence      \n 3 Essex Coun… High confidence       High confidence       High confidence      \n 4 Hudson Cou… High confidence       High confidence       High confidence      \n 5 Ocean Coun… High confidence       High confidence       High confidence      \n 6 Monmouth C… High confidence       High confidence       High confidence      \n 7 Union Coun… High confidence       High confidence       High confidence      \n 8 Camden Cou… High confidence       High confidence       High confidence      \n 9 Passaic Co… High confidence       High confidence       High confidence      \n10 Morris Cou… High confidence       High confidence       High confidence      \n11 Burlington… High confidence       High confidence       High confidence      \n12 Mercer Cou… High confidence       High confidence       High confidence      \n13 Somerset C… High confidence       High confidence       High confidence      \n14 Gloucester… High confidence       High confidence       Moderate             \n15 Atlantic C… High confidence       High confidence       High confidence      \n16 Cumberland… High confidence       High confidence       Low confidence       \n17 Sussex Cou… High confidence       Low confidence        Moderate             \n18 Hunterdon … High confidence       Moderate              Moderate             \n19 Warren Cou… High confidence       Low confidence        Low confidence       \n20 Cape May C… High confidence       Moderate              Low confidence       \n21 Salem Coun… High confidence       Moderate              Low confidence       \n# ℹ 2 more variables: reliability_ttl_hisp <chr>, popE <dbl>\n```\n\n\n:::\n:::\n\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Public Transportation Commuters\nRelbyPop <- county_data %>%\n  group_by(NAME, reliability_transp_white, reliability_transp_black, reliability_transp_asian, reliability_transp_hisp) %>%\n  summarize(\n    popE\n  ) %>%\n  arrange(desc(popE)) %>%\n  print(n = 21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 × 6\n# Groups:   NAME, reliability_transp_white, reliability_transp_black,\n#   reliability_transp_asian [21]\n   NAME     reliability_transp_w…¹ reliability_transp_b…² reliability_transp_a…³\n   <chr>    <chr>                  <chr>                  <chr>                 \n 1 Bergen … High confidence        High confidence        High confidence       \n 2 Middles… High confidence        High confidence        High confidence       \n 3 Essex C… High confidence        High confidence        High confidence       \n 4 Hudson … High confidence        High confidence        High confidence       \n 5 Ocean C… Moderate               Moderate               Low confidence        \n 6 Monmout… High confidence        Moderate               Moderate              \n 7 Union C… High confidence        High confidence        High confidence       \n 8 Camden … High confidence        High confidence        Moderate              \n 9 Passaic… High confidence        High confidence        High confidence       \n10 Morris … High confidence        High confidence        High confidence       \n11 Burling… Moderate               Moderate               Low confidence        \n12 Mercer … High confidence        High confidence        High confidence       \n13 Somerse… Moderate               Moderate               Moderate              \n14 Glouces… High confidence        High confidence        Low confidence        \n15 Atlanti… High confidence        High confidence        High confidence       \n16 Cumberl… Moderate               Low confidence         Moderate              \n17 Sussex … Moderate               Low confidence         Low confidence        \n18 Hunterd… Moderate               Low confidence         Low confidence        \n19 Warren … Moderate               Low confidence         Low confidence        \n20 Cape Ma… Moderate               Low confidence         Low confidence        \n21 Salem C… Low confidence         Moderate               Low confidence        \n# ℹ abbreviated names: ¹​reliability_transp_white, ²​reliability_transp_black,\n#   ³​reliability_transp_asian\n# ℹ 2 more variables: reliability_transp_hisp <chr>, popE <dbl>\n```\n\n\n:::\n:::\n\n \n\n---\n\n## What this means for policy\n\n\nThe fact that smaller counties have lower confidence in their data being accurate can have serious consequences for policy. As can be seen in the charts above, smaller counties like Salem, Cape May, and Warren have lower confidence levels across the ethnicity/race and rider type spectrum; on the other hand, more populated counties, such as Bergen, Middlesex, and Essex, have consistently high confidence levels. When creating commuter policy for the state, residents of Bergen County are more likely to be better served as we have more complete data for them and therefore can more accurately assess their needs. On the other hand, since we have a less accurate understanding of who Salem residents are, we are left more in the dark as to how to assist them. A similar logic carries over by race; since there are more white residents within each county of New Jersey, we can have much higher confidence in the ACS data; on the other hand, since there are far fewer Asian residents, we are unable to rely upon just the ACS to give us guidance to meet their needs. For example, if we were to explore a policy aimed at increasing ridership among Asian commuters in Hunterdon County, where there are an estimated 22 Asian residents and a margin of error of 31, but we only relied on the estimated data and ignored the margin of error, we could end up over-funding in an area in which there are actually no Asian residents at all. On the other hand, in Gloucester County, where there is estimated 160 Asian residents, a margin of error of 140, and low confidence, we could end up either overfunding an areas in which there are actually 20 Asian residents, or under-funding by 87.5% if there were actually 300 Asian residents.\nThe ACS is therefore an excellent tool to get a base understanding of demographics across regions, but it must be used with other outside resource, as on its own it can under- or over-predict for smaller population areas or vulnerable populations.\n",
    "supporting": [
      "assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}